name: mohpromt_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

false_secrets:
  - /example/**
  
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shimmer: ^3.0.0
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  cached_network_image: ^3.3.0
  get: ^4.6.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  centrifuge: ^0.8.0
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.1.3
  uuid: ^3.0.7
  shared_preferences: ^2.0.15
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/element/
    - assets/icon/
